### PR TITLE
Adapt GraphDRP to data length

### PR DESCRIPTION
**Pull request by RylieWeaver**

### CODE REVIEW

**Review by wilke — CHANGES_REQUESTED** [review]
This seems to be a short term fix for a specific configuration. Is it possible to determine those numbers in the init method or as configuration option? Alex made a comment to add this to __init__

**Comment by wilke** [comment]
@adpartin @RylieWeaver9 Can we resolve this, or do we ignore the issue?

**Comment by RylieWeaver** [comment]
> @adpartin @RylieWeaver9 Can we resolve this, or do we ignore the issue?

I would some time to fix as I'm not familiar with GNNs

**Comment by adpartin** [comment]
@wilke @RylieWeaver9 I'm the one who needs to figure this out. We will use original model data for this release, so the dimensions will be hard-coded in the models/ginconv.py. I'll need to fix this problem after the release. I think we can keep it open.

**Pull request closed without merging**
