### PR TITLE
Update graphdrp_baseline_pytorch.py

### PR DESCRIPTION
**Pull request by wilke**
Changed location for dumping values. Please review and delete or accept.

### CODE REVIEW

**Comment by brettin** [comment]
Should we be using candle.file_utils. directory_tree_from_parameters)_

https://www.google.com/url?q=https://github.com/ECP-CANDLE/candle_lib/blob/0d32c6bb97ace0370074194943dbeaf9019e6503/candle/file_utils.py%23L162&sa=D&source=docs&ust=1670423993173305&usg=AOvVaw1K8SymTS106HcRW4qHz1Hy

**Comment by wilke** [comment]
> Should we be using candle.file_utils. directory_tree_from_parameters)_
> 
> https://www.google.com/url?q=https://github.com/ECP-CANDLE/candle_lib/blob/0d32c6bb97ace0370074194943dbeaf9019e6503/candle/file_utils.py%23L162&sa=D&source=docs&ust=1670423993173305&usg=AOvVaw1K8SymTS106HcRW4qHz1Hy

No - the output path is set by candle lib after reading in all parameters from command line and config file. This process should also set the directories if necessary (but should not) since the parameter file is in the same directory by convention.

**Comment by wilke** [comment]
The method is used in args_overwrite_config already.

**Comment by wilke** [comment]
@brettin @jmohdyusof  We can close this PR since it is obsolete. Alex updated directly in develop. @jmohdyusof is the implemented solution acceptable for you? Any changes to the output statement ? 
```print("\nIMPROVE_RESULT val_loss:\t{}\n".format(scores["val_loss"]))```

**Comment by jmohdyusof** [comment]
The print statement is entirely for Supervisor as I understand it, so I don't have any opinion on this. The relevant part for me is directly below:
with open(Path(args.output_dir) / "scores.json", "w", encoding="utf-8") as f:
        json.dump(scores, f, ensure_ascii=False, indent=4)

The candle.directory_tree_from_parameters indeed returns the locations of datadir and outdir. 
Supervisor can modify that path at runtime by specifying --run_id and --experiment_id, respectively. 

It looks like Alex is hand-coding args.output_dir in lines 98-103 which should not be needed.

**Comment by jmohdyusof** [comment]
Also, this code is hard-coding the ftp site (line 106) and doing imports in the middle of the file.

**Comment by wilke** [comment]
> Also, this code is hard-coding the ftp site (line 106) and doing imports in the middle of the file.

@jmohdyusof Can you make an issue for the ftp site and a suggestion, the code is in the candle_data_dir branch ?

**Comment by wilke** [comment]
> The print statement is entirely for Supervisor as I understand it, so I don't have any opinion on this. The relevant part for me is directly below: with open(Path(args.output_dir) / "scores.json", "w", encoding="utf-8") as f: json.dump(scores, f, ensure_ascii=False, indent=4)
> 
> The candle.directory_tree_from_parameters indeed returns the locations of datadir and outdir. Supervisor can modify that path at runtime by specifying --run_id and --experiment_id, respectively.
> 
> It looks like Alex is hand-coding args.output_dir in lines 98-103 which should not be needed.

@jmohdyusof so the code snipped is correct. args is the results from initialize_parameters() which calls candle.directory_tree_from_parameters in the deeps.

**Comment by jmohdyusof** [comment]
I would argue this code is not needed. (args.output_dir will always be set, and the directory will always exist, if directory_tree_from_parameters has been called:

# Create output dir
    if args.output_dir is not None:
        outdir = Path(args.output_dir)
    else:
        outdir = fdir / "results"
    os.makedirs(outdir, exist_ok=True)

**Comment by adpartin** [comment]
Code already develop branch. No merging. Closing PR.

**Pull request closed without merging**
